// <auto-generated />
namespace AssetManagement.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CommentOwner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentOwner));
        
        string IMigrationMetadata.Id
        {
            get { return "201608111730025_CommentOwner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
