// <auto-generated />
namespace AssetManagement.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddStock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStock));
        
        string IMigrationMetadata.Id
        {
            get { return "201603261114465_AddStock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
