// <auto-generated />
namespace AssetManagement.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Clean : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Clean));
        
        string IMigrationMetadata.Id
        {
            get { return "201610110840231_Clean"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
